services:
  app:
    build: .
    container_name: sboot-api-wishlist
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    # Aguarda a porta do Mongo antes de iniciar a aplicação
    command: ["sh", "-c", "until nc -z mongo 27017; do echo 'Aguardando Mongo...'; sleep 2; done; java -jar app.jar"]
    restart: on-failure
    environment:
      # Sobrescreve application.properties para usar o host `mongo`
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}

  mongo:
    image: mongo:8.0
    container_name: wishlist-mongo
    restart: always
    ports:
      - "27017:27017"
    command: [ "mongod", "--bind_ip", "0.0.0.0" ]
    healthcheck:
      test: ["CMD-SHELL", "bash -c '> /dev/tcp/localhost/27017' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: