services:
  app:
    build: .
    container_name: sboot-api-wishlist
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      # Sobrescreve application.properties para usar o host `mongo`
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}

  mongo:
    image: mongo:8.0
    container_name: wishlist-mongo
    restart: always
    ports:
      - "27017:27017"
    command: [ "mongod", "--bind_ip", "0.0.0.0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: